Repository assignment-sparta/budget-management-project, pull requests merged in 2025-02, with the labels that each got.

#10 chore: 장고 프로젝트 초기 세팅
  budget_management_project/__init__.py
  budget_management_project/account/__init__.py
  budget_management_project/account/apps.py
  budget_management_project/account/migrations/__init__.py
  budget_management_project/account/models.py
  budget_management_project/account/serializers.py
  budget_management_project/account/tests.py
  budget_management_project/account/urls.py
  budget_management_project/account/views.py
  budget_management_project/budget/__init__.py
  budget_management_project/budget/apps.py
  budget_management_project/budget/migrations/__init__.py
  budget_management_project/budget/models.py
  budget_management_project/budget/serializers.py
  budget_management_project/budget/tests.py
  budget_management_project/budget/urls.py
  budget_management_project/budget/views.py
  budget_management_project/expense/__init__.py
  budget_management_project/expense/apps.py
  budget_management_project/expense/migrations/__init__.py
  budget_management_project/expense/models.py
  budget_management_project/expense/serializers.py
  budget_management_project/expense/tests.py
  budget_management_project/expense/urls.py
  budget_management_project/expense/views.py
  config/__init__.py
  config/asgi.py
  config/root_urls.py
  config/settings.py
  config/wsgi.py
  manage.py
  requirements.txt
Labels: ⚙️ chore

#15 chore: User 모델 초기 마이그레이션 추가
  budget_management_project/account/migrations/0001_initial.py
Labels: ⚙️ chore

#20 chore: requirements.txt 추가 및 settings.py 일부 수정
  config/settings.py
  requirements.txt
Labels: ⚙️ chore

#18 feat: 예산 설정 관련 기능
  budget_management_project/budget/models.py
  budget_management_project/budget/serializers.py
  budget_management_project/budget/urls.py
  budget_management_project/budget/views.py
  config/root_urls.py
Labels: ✨ feat

#17 feat: 지출 관련 기능 구현
  budget_management_project/expense/migrations/0001_initial.py
  budget_management_project/expense/models.py
  budget_management_project/expense/permissions.py
  budget_management_project/expense/serializers.py
  budget_management_project/expense/urls.py
  budget_management_project/expense/views.py
Labels: ✨ feat

#21 feat: Enum 기능 추가
  budget_management_project/commons/__init__.py
  budget_management_project/commons/apps.py
  budget_management_project/commons/enums.py
  budget_management_project/commons/migrations/__init__.py
  budget_management_project/expense/enums.py
  budget_management_project/expense/views.py
  config/settings.py
Labels: ✨ feat

#23 feat: budget 모델 마이그레이션 파일
  budget_management_project/budget/migrations/0001_initial.py
Labels: ✨ feat

#26 refact: budget앱 전체적인 코드 리팩토링
  budget_management_project/budget/migrations/0001_initial.py
  budget_management_project/budget/serializers.py
  budget_management_project/budget/urls.py
  budget_management_project/budget/views.py
  budget_management_project/expense/migrations/0001_initial.py
  budget_management_project/expense/models.py
  budget_management_project/expense/serializers.py
  budget_management_project/expense/views.py
  config/root_urls.py
Labels: 🐛 bug, ✨ feat, ♻️ refactor

#27 feat: 지출 기록 관련 나머지 API 기능 추가
  budget_management_project/expense/migrations/0001_initial.py
  budget_management_project/expense/models.py
  budget_management_project/expense/serializers.py
  budget_management_project/expense/urls.py
  budget_management_project/expense/views.py
  config/settings.py
  docker-compose.yml
Labels: 🐛 bug, ✨ feat, ♻️ refactor

#25 feat: 로그인 기능 구현
  budget_management_project/account/serializers.py
  budget_management_project/account/urls.py
  budget_management_project/account/views.py
Labels: ✨ feat

#28 refact: 카테고리 모델 generic뷰로 변경 및 자동 카테고리 생성
  budget_management_project/budget/serializers.py
  budget_management_project/expense/models.py
  budget_management_project/expense/views.py
Labels: ♻️ refactor

#29 feat: 로그인 및 토큰 URL을 account 경로로 통일
  budget_management_project/account/urls.py
Labels: ✨ feat

#32 feat: expense 조회 기능 추가
  budget_management_project/expense/serializers.py
Labels: ✨ feat

#31 Feature/expense consulting
  budget_management_project/budget/migrations/0001_initial.py
  budget_management_project/commons/enums.py
  budget_management_project/expense/consulting.py
  budget_management_project/expense/migrations/0001_initial.py
  budget_management_project/expense/migrations/0002_expense_is_excluded.py
  budget_management_project/expense/migrations/0003_update_category_types.py
  budget_management_project/expense/views.py
  budget_management_project/manage.py
Labels: ✨ feat

#33 feat: 예산 추천 기능 추가
  budget_management_project/budget/serializers.py
  budget_management_project/budget/urls.py
  budget_management_project/budget/views.py
  config/root_urls.py
Labels: ✨ feat, ♻️ refactor

#34 docs: README 작성
  README.md
  manage.py
Labels: 🐛 bug, 📝 docs

#37 feat: 지출 통계 API 추가
  budget_management_project/expense/serializers.py
  budget_management_project/expense/urls.py
  budget_management_project/expense/views.py
Labels: ✨ feat
